/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ProcessQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ProcessWorker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WebApp": {
      "type": "sst.aws.React"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}