# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class ProcessQueue:
        type: str
        url: str
    class SQSProcessorFunction:
        name: str
        type: str
    class SmultiApp:
        type: str
        url: str
    class SmultiBucket:
        name: str
        type: str
    class SmultiVPC:
        type: str

