# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class Bucket:
        name: str
        type: str
    class ProcessQueue:
        type: str
        url: str
    class ProcessWorker:
        name: str
        type: str
    class WebApp:
        type: str
        url: str

